### ISSUE TITLE
DATA LOSS! "Cancel" button renames everything "null"

### ISSUE THREAD

**Issue by semiconducted** [webkul/renamer#2]
Sketch 52.5 (67469)

Choosing "Cancel" button on Symbols page with Symbol Masters selected renames everything as 'null'. 
Bad news, but undo stack still works, so loss is recoverable.

**Comment by webkul-nitish** [comment]
Thanks for the report. I have just fixed this bug in the latest update. Possible You could have received a notification in SketchApp for Plugin Update or you [download updated version from the release section](https://github.com/webkul/renamer/releases/download/v1.0.5/renamer.sketchplugin.zip).
